### ISSUE TITLE
BUG: Pressing return in ip address box causes screen to flicker, not connect

### ISSUE THREAD

**Issue by AlexMulkerrin** [AJLProjects/SuSeGa#3]
Seems to be some issue with the ip connect input box.

Pressing return once you have entered the ip does not initiate the connection but the connect button will then cause the client to enter a weird state where it is very quickly connecting and disconnecting, making the skybox flicker from orange to blue.
A strange debug string can also be seen on the screen: 'qweqweqwe?'

Client must be terminated to remove this bug.

**Comment by AJLProjects** [comment]
Fixed, was using Time.deltatime instead of Time.time.

**Comment by AlexMulkerrin** [comment]
tricksy little delta ;)
